name: client
description: "Collaborative Intermediate Output Automatic Archive Program"
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  file_picker: ^5.2.2
  http: 1.2.2
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  assets:
    - images/logo_eodirok1.png
  uses-material-design: true

fonts:
  - family: Pretendard
    fonts:
      - asset: assets/fonts/PretendardRegular.ttf
        weight: 700